openapi: 3.0.3
info:
  title: Cohorty API
  version: 1.0.0
  description: API for Cohorty, where leading educators track student progress though
    their courses.
paths:
  /:
    get:
      operationId: root_retrieve
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /{course_id}/assignment/{id}/:
    get:
      operationId: assignment_retrieve
      parameters:
      - in: path
        name: course_id
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - assignment
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssignmentDetail'
          description: ''
    put:
      operationId: assignment_update
      parameters:
      - in: path
        name: course_id
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - assignment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignmentDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AssignmentDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AssignmentDetail'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssignmentDetail'
          description: ''
    patch:
      operationId: assignment_partial_update
      parameters:
      - in: path
        name: course_id
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - assignment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedAssignmentDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedAssignmentDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedAssignmentDetail'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssignmentDetail'
          description: ''
    delete:
      operationId: assignment_destroy
      parameters:
      - in: path
        name: course_id
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - assignment
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /{course_id}/staff/{user_id}/:
    get:
      operationId: staff_list
      parameters:
      - in: path
        name: course_id
        schema:
          type: integer
        required: true
      - in: path
        name: user_id
        schema:
          type: integer
        required: true
      tags:
      - staff
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CourseStaff'
          description: ''
    post:
      operationId: staff_create
      parameters:
      - in: path
        name: course_id
        schema:
          type: integer
        required: true
      - in: path
        name: user_id
        schema:
          type: integer
        required: true
      tags:
      - staff
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseStaff'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CourseStaff'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CourseStaff'
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseStaff'
          description: ''
  /{course_id}/student-enrollment/{user_id}/:
    get:
      operationId: student_enrollment_list
      parameters:
      - in: path
        name: course_id
        schema:
          type: integer
        required: true
      - in: path
        name: user_id
        schema:
          type: integer
        required: true
      tags:
      - student-enrollment
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StudentEnrollment'
          description: ''
    post:
      operationId: student_enrollment_create
      parameters:
      - in: path
        name: course_id
        schema:
          type: integer
        required: true
      - in: path
        name: user_id
        schema:
          type: integer
        required: true
      tags:
      - student-enrollment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentEnrollment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/StudentEnrollment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/StudentEnrollment'
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentEnrollment'
          description: ''
  /{course_id}/student/{id}/:
    get:
      operationId: student_retrieve
      parameters:
      - in: path
        name: course_id
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - student
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDetail'
          description: ''
  /{id}/:
    get:
      operationId: root_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          description: ''
    put:
      operationId: root_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Course'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          description: ''
    patch:
      operationId: root_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCourse'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCourse'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCourse'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          description: ''
    delete:
      operationId: root_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /{id}/assignment/:
    post:
      operationId: assignment_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - assignment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignmentList'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AssignmentList'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AssignmentList'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssignmentList'
          description: ''
  /{id}/assignments/:
    get:
      operationId: assignments_list
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - assignments
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AssignmentList'
          description: ''
    post:
      operationId: assignments_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - assignments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignmentList'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AssignmentList'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AssignmentList'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssignmentList'
          description: ''
  /{id}/students/:
    get:
      operationId: students_list
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - students
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
          description: ''
    post:
      operationId: students_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - students
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Student'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Student'
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
  /course/:
    post:
      operationId: course_create
      tags:
      - course
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Course'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          description: ''
  /courses/:
    get:
      operationId: courses_list
      tags:
      - courses
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
          description: ''
    post:
      operationId: courses_create
      tags:
      - courses
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Course'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          description: ''
  /users/login/:
    post:
      operationId: users_login_create
      tags:
      - users
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /users/token/refresh/:
    get:
      operationId: users_token_refresh_retrieve
      tags:
      - users
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
components:
  schemas:
    AssignmentDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        due_date:
          type: string
          format: date
        submissions:
          type: array
          items:
            $ref: '#/components/schemas/Submission'
          readOnly: true
      required:
      - due_date
      - id
      - name
      - submissions
    AssignmentList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        due_date:
          type: string
          format: date
      required:
      - due_date
      - id
      - name
    Course:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        students:
          type: array
          items:
            $ref: '#/components/schemas/Student'
          readOnly: true
        assignments:
          type: array
          items:
            $ref: '#/components/schemas/AssignmentList'
          readOnly: true
      required:
      - assignments
      - id
      - name
      - students
    CourseStaff:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          type: integer
          readOnly: true
        course:
          type: integer
          readOnly: true
      required:
      - course
      - id
      - user
    PatchedAssignmentDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        due_date:
          type: string
          format: date
        submissions:
          type: array
          items:
            $ref: '#/components/schemas/Submission'
          readOnly: true
    PatchedCourse:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        students:
          type: array
          items:
            $ref: '#/components/schemas/Student'
          readOnly: true
        assignments:
          type: array
          items:
            $ref: '#/components/schemas/AssignmentList'
          readOnly: true
    Student:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          readOnly: true
        assignment_percentage:
          type: string
          readOnly: true
        absences:
          type: string
          readOnly: true
      required:
      - absences
      - assignment_percentage
      - id
      - name
    StudentDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          readOnly: true
        submissions:
          type: string
          readOnly: true
        attendance:
          type: string
          readOnly: true
      required:
      - attendance
      - id
      - name
      - submissions
    StudentEnrollment:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          type: integer
          readOnly: true
        course:
          type: integer
          readOnly: true
      required:
      - course
      - id
      - user
    Submission:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        student:
          type: integer
        is_complete:
          type: boolean
        assignment:
          type: integer
      required:
      - assignment
      - id
      - student
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
